In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [7]:
model = keras.Sequential(
    [
        layers.Dense(2,activation = 'relu',name = 'layer1'),
        layers.Dense(3, activation = 'relu', name = 'layer2'),
        layers.Dense(4, name = 'layet3')
        
    ]
)
x = tf.ones((3,3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.64961475,  0.02863168, -0.21038237,  0.6071898 ],
       [ 0.64961475,  0.02863168, -0.21038237,  0.6071898 ],
       [ 0.64961475,  0.02863168, -0.21038237,  0.6071898 ]],
      dtype=float32)>

In [11]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_tesy = x_train/255.0,x_test/255.0
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(128,activation = 'relu'))
model.add(tf.keras.layers.Dropout(0.2))#随机丢弃避免过拟合
model.add(tf.keras.layers.Dense(10,activation="softmax"))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=5)
model.evaluate(x_test,y_test,verbose=2)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2967 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1451 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1088 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0900 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0725 - accuracy: 0.9768
313/313 - 0s - loss: 14.2210 - accuracy: 0.9749


[14.221033096313477, 0.9749000072479248]

In [13]:
class cat:
    def __init__(self, name):
        self.name = name
    def speak(self):
        print("我是%s" %(self.name))
class black_cat(cat):
    def __init__(self, name, age):
        cat.__init__(self,name)
        self.age = age
    def speak(self):
        print("我是%s，我%d岁了"%(self.name,self.age))
        
s = cat('A')
s.speak()
s2 = black_cat("B",12)
s2.speak()

我是A
我是B，我12岁了


In [20]:
a = tf.random.normal([4,])
b = tf.random.normal([4,1])
a,b

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.783326 ,  2.0196269,  2.1668994, -1.2422489], dtype=float32)>,
 <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[-0.5395514 ],
        [ 0.39849716],
        [-1.9209759 ],
        [-0.33339927]], dtype=float32)>)

In [19]:
b

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 2.4926577],
       [ 1.907159 ],
       [ 1.7571728],
       [-1.3040956]], dtype=float32)>