In [11]:
import tensorflow as tf
from datetime import datetime
%load_ext tensorboard
%reload_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [13]:
class Dense(tf.Module):
    def __init__(self, name = None):
        super().__init__(name = name)
        self.w = tf.Variable(
            [[-3.14,-2.31,2.16]],name = 'w')
        self.b = tf.Variable([[0, 0, 0]],name = 'b')
    @tf.function
    def __call__(self,x):
        y = tf.matmul(self.w, x) #+ self.b
        return tf.nn.sigmoid(y)
    
w = tf.constant([[-3.14,-2.31,2.16]])
b = tf.constant([0, 0, 0])
dense = Dense(name = 'pred')
dense(tf.constant([[0.0288],[-0.3256],[0.5925]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.8745173]], dtype=float32)>

In [3]:
w = tf.constant([[1, 1, 1]])
x = tf.constant([[1],[2],[3]])
               
tf.matmul(w,x)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[6]])>

In [3]:
class Dense(tf.Module):
    def __init__(self, w, b, name = None):
        super().__init__(name = name)
        self.w = tf.Variable(
            tf.random.normal([w,b]),name = 'w')
        self.b = tf.Variable(tf.random.normal([w,b]),name = 'b')
    def __call__(self,x):
        y = tf.matmul(self.w, x) + self.b
        return tf.nn.sigmoid(y)


class SequceMoudle(tf.Module):
    def __init__(self, name = None):
        super().__init__(name = name)
        
        self.dense_1 = Dense(w= 3, b = 3)
        self.dense_2 = Dense(w = 1, b = 3)
    @tf.function
    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)
    
my_model = SequceMoudle(name = 'ss')
my_model(tf.constant([[0.0288],[-0.3256],[0.5925]]))
        

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.9280833, 0.6626529, 0.8103927]], dtype=float32)>

In [7]:
chkp = 'my_chec'
checkpoint = tf.train.Checkpoint(model = dense)
checkpoint.write(chkp)

'my_chec'

In [1]:
stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = "logs/func/%s" % stamp
writer = tf.summary.create_file_writer(logdir)

new_model = Dense()
tf.summary.trace_on(graph = True, profiler = True)
z = print(new_model(tf.constant([[0.0288],[-0.3256],[0.5925]])))
with writer.as_default():
    tf.summary.trace_export(
        name = "my_func_trace",
        step = 0,
        profiler_outdir=logdir
        )
%tensorboard --logdir logs/func

NameError: name 'datetime' is not defined

In [12]:
tf.__version__

'2.3.1'

In [14]:
stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = "logs/func/%s" % stamp
writer = tf.summary.create_file_writer(logdir)

new_model = SequceMoudle()
tf.summary.trace_on(graph = True, profiler = True)
z = print(new_model(tf.constant([[0.0288],[-0.3256],[0.5925]])))
with writer.as_default():
    tf.summary.trace_export(
        name = "my_func_trace",
        step = 0,
        profiler_outdir=logdir
        )
%tensorboard --logdir logs/func

TypeError: __init__() got an unexpected keyword argument 'w'

In [8]:
!kill 19496

'kill' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
