In [1]:
import tensorflow as tf
import tensorflow.keras

from tensorflow.keras import layers, losses, optimizers, Sequential

In [7]:
x = tf.range(10)
print(x)
x = tf.random.shuffle(x)
net = layers.Embedding(10,4)
out = net(x)
out

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[-0.02961577,  0.04216763,  0.00344759,  0.0359213 ],
       [ 0.02188409,  0.04180696, -0.00398189, -0.04123566],
       [-0.03922368,  0.01668391, -0.0301054 , -0.03916217],
       [-0.04543224, -0.00393929,  0.0128033 , -0.01016439],
       [ 0.02683202, -0.01638564, -0.03658943, -0.02024445],
       [-0.03176405,  0.02756492,  0.0281246 , -0.01937221],
       [-0.03276704,  0.02818235,  0.02178252,  0.04620827],
       [ 0.01619383, -0.00105233,  0.00969006, -0.01922562],
       [-0.00198622,  0.02890385,  0.03815775, -0.03910955],
       [ 0.0498397 ,  0.02408623, -0.04270862, -0.04685039]],
      dtype=float32)>

In [8]:
net.embeddings

<tf.Variable 'embedding_1/embeddings:0' shape=(10, 4) dtype=float32, numpy=
array([[ 0.01619383, -0.00105233,  0.00969006, -0.01922562],
       [-0.03276704,  0.02818235,  0.02178252,  0.04620827],
       [-0.00198622,  0.02890385,  0.03815775, -0.03910955],
       [-0.03922368,  0.01668391, -0.0301054 , -0.03916217],
       [ 0.0498397 ,  0.02408623, -0.04270862, -0.04685039],
       [ 0.02683202, -0.01638564, -0.03658943, -0.02024445],
       [-0.04543224, -0.00393929,  0.0128033 , -0.01016439],
       [ 0.02188409,  0.04180696, -0.00398189, -0.04123566],
       [-0.02961577,  0.04216763,  0.00344759,  0.0359213 ],
       [-0.03176405,  0.02756492,  0.0281246 , -0.01937221]],
      dtype=float32)>

In [10]:
cell = layers.SimpleRNNCell(3)
cell.build(input_shape = (None,4))
cell.trainable_variables

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[-0.5027132 ,  0.6620033 ,  0.12959373],
        [ 0.56586933, -0.2874576 , -0.20037037],
        [ 0.5140486 , -0.80447626,  0.16425765],
        [-0.43943116, -0.14867848,  0.61983716]], dtype=float32)>,
 <tf.Variable 'recurrent_kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[-0.24463332,  0.9590473 ,  0.14276786],
        [ 0.96929663,  0.24566406,  0.01063761],
        [-0.02487097,  0.14098673, -0.98969907]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]