In [14]:
import numpy as np
import tensorflow as tf

In [6]:
A =  np.random.randint(10, size=(3, 3))
A =  np.random.randint(10, size=(2, 3, 4))
A

array([[[4, 2, 5, 5],
        [6, 7, 3, 1],
        [5, 1, 8, 6]],

       [[0, 7, 4, 2],
        [9, 8, 2, 9],
        [8, 2, 6, 5]]])

In [13]:
x = np.array([22,35,86])
W1 = np.random.randint(10,size = (3,3))
W2 = np.random.randint(10, size = (2,3))
y = np.dot(W2,np.dot(W1,x))
y

array([ 8315, 17607])

In [18]:
tf.constant([1,3,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 3])>

In [20]:
tf.constant([[1,2],
            [3,4],
            [5,6]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [21]:
tf.random.normal([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-1.4219494 ,  0.19962718,  0.795519  ,  1.0713714 ],
       [ 0.64298373,  0.16521473, -0.5913153 ,  0.55314785],
       [-1.606017  , -1.0469449 ,  1.7008187 ,  0.7339621 ],
       [ 0.2889139 , -0.33418536,  1.9213187 , -0.79617506]],
      dtype=float32)>

In [22]:
tf.random.normal([4,5,6])

<tf.Tensor: shape=(4, 5, 6), dtype=float32, numpy=
array([[[-0.46677303,  0.4314998 ,  1.0164458 ,  0.56780326,
         -1.2579349 ,  0.9432379 ],
        [-0.50176966,  0.62541306,  0.10273376, -2.4389775 ,
         -0.27323484,  0.6415897 ],
        [-1.212178  ,  0.30436802,  0.10282056, -1.1749554 ,
          1.4242604 , -0.3219256 ],
        [-0.36096624,  0.07868027,  1.5238116 , -0.65154505,
          0.14318174,  0.8864308 ],
        [ 0.5363786 , -0.12080996, -0.28463626, -0.53843737,
          0.923112  , -0.65019196]],

       [[ 0.00755003,  0.71976453, -1.0752836 ,  1.3163055 ,
         -1.160079  ,  0.9309412 ],
        [ 0.6246599 ,  0.74764156,  0.80710834, -1.8873684 ,
         -0.98103476,  1.6380117 ],
        [ 1.1735942 ,  0.85249305, -1.5080464 ,  0.38521147,
         -1.8057642 ,  1.0838171 ],
        [ 1.7236524 , -1.3299032 ,  1.4735434 , -0.17230794,
         -0.40876338,  0.15033221],
        [ 0.82292295,  1.6803334 ,  0.50062937,  0.8380173 ,
         -0.4

In [24]:
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,2],
                [3,4]])
print(a*b)
print(a@b)

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [26]:
·形状：张量的每个维度的长度
·秩：张量的维度数量
·轴：张量的一个特殊维度


SyntaxError: invalid character in identifier (<ipython-input-26-f9930807553c>, line 1)

In [31]:
A = tf.random.normal([1,3,2])
A

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[-0.45500013, -0.28969118],
        [-0.72899413,  0.15903997],
        [ 1.2459145 , -0.5031812 ]]], dtype=float32)>

In [35]:
A[0,-1,-1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.5031812>

In [38]:
ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]
]

ragged_tensor = tf.ragged.constant(ragged_list)
ragged_tensor

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

In [39]:
print(tf.debugging.set_log_device_placement)

<function set_log_device_placement at 0x000002AD6A881E58>


In [55]:
a = tf.constant([[1,2],
                [3,4],
                [5,6]])
a_variable = tf.Variable(a)
print(tf.argmax(a_variable))
print(tf.argmax(a_variable,0))
print(tf.argmax(a_variable,1))
print(tf.argmax(a))
print(tf.argmax(a,0))
print(tf.argmax(a,1))

tf.Tensor([2 2], shape=(2,), dtype=int64)
tf.Tensor([2 2], shape=(2,), dtype=int64)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)
tf.Tensor([2 2], shape=(2,), dtype=int64)
tf.Tensor([2 2], shape=(2,), dtype=int64)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)


In [56]:
x = tf.ones((2,2))

In [58]:
x = tf.constant(1.0)
with tf.GradientTape(persistent = True) as t:
    t.watch(x)
    y = x**2+tf.exp(x)
dy_dx = t.gradient(y,x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=4.7182817>